services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules/
  xivapi-explorer:
    build: ./xivapi-explorer
    container_name: xivapi-explorer
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./xivapi-explorer
        target: /app
      - /app/node_modules/
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend
        target: /app
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin:
