[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.mypy]
python_version = 3.12
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_calls = True
disallow_untyped_defs = True
